[UPSTREAM] Fix new LLVM 11 integrated assembler error
LLVM has become more strict when parsing .section directives and now
expects SHT_X86_64_UNWIND for .eh_frame on amd64. Without this change we
get the following:
error: changed section type for .eh_frame, expected: 0x70000001.