Allow building with CHERI-LLVM prior to the Sep 2021 merge
The previous version of clang was a LLVM13 snapshot before the commit
that added Wunused-but-set-variable. This means that adding
-Wno-error=unused-but-set-variable for ${COMPILER_VERSION} >= 130000
will result in a -Werror build failure:
error: unknown warning option '-Werror=unused-but-set-variable'.

Convert the version checks to a COMPILER_FEATURES check instead. It
probably doesn't make much sense to upstream this change since the
unused-but-set-variable warnings will eventually be fixed.