[DO NOT MERGE] Jenkinsfile: don't build non-Morello targets
The branch does not build with the dev branch of llvm due to errors in
C++ type traits code:
error: keyword '__is_referenceable' will be made available as an identifier for the remainder of the translation unit [-Werror,-Wkeyword-compat]

The kernel-c18n branch does build with the c18n_policy llvm-morello
branch. However, I must rebase the kernel-c18n branch onto a newer dev
in due course. Let's not build non-Morello targets on Jenkins for now.