swab: Correctly annotate the data as misaligned.
Previously, this marked the raw pointers as being misaligned, not the
data being pointed to.  GNU attributes are a bit tricky, so use a
typedef to attach the alignment to the data.  This fixes the build on
CHERI architectures which do not support misaligned pointers and were
thus failing with:

lib/libc/string/swab.c:12:18: error: alignment (1) of 'const uint16_t *' (aka 'const unsigned short *') is less than the required capability alignment (16) [-Werror,-Wcheri-capability-misuse]
   12 |         const uint16_t *f __aligned(1) = from;
      |

Sponsored by:	AFRL, DARPA