GitHub actions: unbreak macOS build
Error: llvm 11.0.0 is already installed

Also make the linking failure non-fatal:

Error: The `brew link` step did not complete successfully

(cherry picked from commit 40903394bf48c916f0790fac8a2cde5c487a2676)