Avoid adding .o files to the link command twice in libc
Until recently these duplicate .o files were filtered out by lorder.sh, but
with my change to use ar -s instead (21fd74540ca1fc7475392612a2e097564b21a0d8),
we now get the following errors:

ld.lld: error: duplicate symbol: __sys_fcntl
>>> defined at _fcntl.S:3
>>>            _fcntl.pico:(__fcntl_compat)
>>> defined at _fcntl.S:3
>>>            _fcntl.pico:(.text+0x0)

ld.lld: error: duplicate symbol: __sys_ioctl
>>> defined at _ioctl.S:3
>>>            _ioctl.pico:(__sys_ioctl)
>>> defined at _ioctl.S:3
>>>            _ioctl.pico:(.text+0x0)

ld.lld: error: duplicate symbol: __sys_open
>>> defined at _open.S:3
>>>            _open.pico:(__sys_open)
>>> defined at _open.S:3
>>>            _open.pico:(.text+0x0)

ld.lld: error: duplicate symbol: __sys_openat
>>> defined at _openat.S:3
>>>            _openat.pico:(__sys_openat)
>>> defined at _openat.S:3
>>>            _openat.pico:(.text+0x0)


Fortunately this is fixed easily: we do not need to add ${S_NU} to OBJS,
since it is already included in SRCS two lines above. This unnecessary
assignment has existed since the wrappers were first added in 93aaf8abd9e98bbe68944925577b5814593e5fbd

Co-authored-by: Jessica Clarke <jrtc27@jrtc27.com>