Fix build of statically linked tftpd
The read_init function name conflicts with libedit:

ld.lld: error: duplicate symbol: read_init
>>> defined at tftp-file.c:219 (.../cheribsd/libexec/tftpd/tftp-file.c:219)
>>>            tftp-file.o:(read_init)
>>> defined at read.c:85 (.../cheribsd/contrib/libedit/read.c:85)
>>>            read.o:(.text+0x0) in archive .../cheribsd/riscv.riscv64c/tmp/usr/lib/libedit.a